mongo-host:
  172.16.81.1
mongo-db:
  mesomelas-history
mongo-test-host:
  172.16.81.1
mongo-test-db:
  mesomelas-test-history
topix:
    http://www.topix.net/rss/search/article?x=0&y=0&q=
twitter:
    http://search.twitter.com/trends.json